name: Export PDFs

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get necessary packages for this image
      - uses: actions/checkout@v3
      - name: Install necessary packages
        run: sudo apt-get install graphicsmagick -y

      # Get latest chrome
      - name: Get Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      # Check out the code
      - name: Checkout
        uses: actions/checkout@v3.0.0

      # Get appropriate nodejs version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      # Restore packages and build
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules
      - name: Restore Asset Caches
        uses: actions/cache@v2
        with:
          key: if-cache
          path: |
            ./if-cache
            ./if-cache.json
            ./twitter-cache.json
      - run: npm i
        
      - name: Run build
        run: npm run build
        
      # Create a "dummy" http server inside the container
      # on the output folder of the build
      - name: Launch HTTP Server
        uses: Eun/http-server-action@v1.0.3
        with:
          directory: dist

      # Launch a headless chrome instance for exporting
      - name: (EN) Get PDF from HTML
        run: |
          google-chrome --headless --print-to-pdf-no-header \
          --run-all-compositor-stages-before-draw --print-to-pdf="public/gdb-en.pdf" \
          http://localhost:8080/en/printable/index.html
          
      - name: (CN) Get PDF from HTML
        run: |
          google-chrome --headless --print-to-pdf-no-header \
          --run-all-compositor-stages-before-draw --print-to-pdf="public/gdb-cn.pdf" \
          http://localhost:8080/zh/printable/index.html
          
      - name: (DE) Get PDF from HTML
        run: |
          google-chrome --headless --print-to-pdf-no-header \
          --run-all-compositor-stages-before-draw --print-to-pdf="public/gdb-de.pdf" \
          http://localhost:8080/de/druckbar/index.html

      - name: (HU) Get PDF from HTML
        run: |
          google-chrome --headless --print-to-pdf-no-header \
          --run-all-compositor-stages-before-draw --print-to-pdf="public/gdb-hu.pdf" \
          http://localhost:8080/hu/nyomtathato/index.html
          
      - name: (PL) Get PDF from HTML
        run: |
          google-chrome --headless --print-to-pdf-no-header \
          --run-all-compositor-stages-before-draw --print-to-pdf="public/gdb-pl.pdf" \
          http://localhost:8080/pl/do-druku/index.html
        
      # Something is coming soon ;)
#      - name: (FR) Get PDF from HTML
#        run: |
#          google-chrome --headless --print-to-pdf-no-header \
#          --run-all-compositor-stages-before-draw --print-to-pdf="public\gdb-fr.pdf" \
#          http://localhost:8080/fr/a-imprimer/index.html
        
      # Commit the new pdfs
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          cd public
          git add -A *.pdf
          git commit -m "Adding exported PDFs"
        shell: bash
        
      # Push files back to the SCM
      # Temporarily it pushes to a branch, for:
      #  * not to put built files immediately to the public server,
      #    letting a manual re-verification whether the exported pdf is "okay"
      #  * to not to relaunch another github action based on this push,
      #    potentially creating a loop (to check).
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: adeeena/GenderDysphoria.fyi
          branch: export-pdfs
          force: true
